### ISSUE TITLE
ERROR in Conflict: Multiple assets emit different content to the same filename manifest.json 

### ISSUE THREAD

**Issue by addamove** [shellscape/webpack-manifest-plugin#251]
Hello!
I tried to use this plugin with webpack 5 and webpacker 6 and if I use it I have this error. Commenting plugin and everything works.
Do you have any ideas how can I try to debug this issue?
 
ERROR in Conflict: Multiple assets emit different content to the same filename manifest.json

**Comment by shellscape** [comment]
_If you are sure this is a bug or documentation issue, please take the time to refile this issue **using the issue template**._

Hey there, thanks for opening an issue - Unfortunately you missed (or may have disregarded) the message about issue templates being _required_. Because our issue template was removed, we assume that this is a support request, and that's not something we offer here. Also, if you refile, please don't ignore Issue sections. They're in the template because they're useful to the maintainers of this project.

**Comment by dac09** [comment]
Hello, I know this is closed, but I wanted to comment here incase someone else comes across this.

I've experienced this issue on webpack 5, using RedwoodJS (which uses this under the hood). The problem was that my public folder already had a `manifest.json` - so when this plugin tries to produce another manifest, it caused the build to fail.

I configured the output path like this 
```
        new WebpackManifestPlugin({
          fileName: 'rw-build-manifest.json', // different filename
        }),
```

and now the error is gone :)
